### ISSUE TITLE
URL needs to be updated.

### ISSUE THREAD

**Issue by mworthley** [pop-os/system76-driver#128]
https://github.com/pop-os/system76-driver/blob/fc68c7593dadfeeb6af7446592455a0def7c4f1f/system76-firmware-dialog#L199

`s76.co/lfw` leads to a 404 page. I believe the URL needs to be updated to `s76.co/sfu`

**Comment by ahoneybun** [comment]
I'm not seeing this in master any longer so I don't believe this bug applies to the project now.

**Comment by brs17** [comment]
This firmware dialog has been replaced with https://github.com/pop-os/firmware-manager/
