### ISSUE TITLE
Touchpad freezes after a while

### ISSUE THREAD

**Issue by HuangLiPang** [pop-os/system76-driver#130]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
I am using Acer K50-20 laptop with Pop_Os! 18.04 LTS. The touchpad works fine when the laptop powers on. But after a while, the touchpad will freeze and cannot work. 

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by crawfxrd** [comment]
Not System76 hardware.
