### ISSUE TITLE
`system76-driver-cli` generates malformed file in `modprobe.d` on oryp7/Manjaro

### ISSUE THREAD

**Issue by MilesBHuff** [pop-os/system76-driver#197]
**Distribution (run `cat /etc/os-release`):**
 ```
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux
```
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
`system76-driver 20.04.31-1`

**Issue/Bug Description:**
On oryp7, running `system76-driver-cli` generates a malformed `/etc/modprobe.d/s76-i915-mkinitcpio.conf` file:
```
# Added by system76-driver
options i915
```

**Other Notes:**
`mkinitcpio` (as run by `system76-driver-cli`) gives the following error:
```
libkmod: kmod_config_parse: /etc/modprobe.d/s76-i915-mkinitcpio.conf line 2: ignoring bad line starting with 'options'
```

**Comment by crawfxrd** [comment]
This is a bug in the patch applied to the package on AUR. We don't maintain that.
