### ISSUE TITLE
V day - thnk about system76-driver snap :D

### ISSUE THREAD

**Issue by coverme76** [pop-os/system76-driver#21]
**Other Notes**
![screenshot_2018-02-14_03-01-12](https://user-images.githubusercontent.com/36464680/36186270-eef5d330-1135-11e8-9da2-01b46af58ae3.png)

Source: https://youtu.be/9IfgX-k7Hag?t=10m1s

**Comment by brs17** [comment]
We are very intrigued and interested to see where and how the Snaps and Flatpak technologies develop but for the time being we are continuing to package .debs
