### ISSUE TITLE
where can I find system76-adjust-tdp

### ISSUE THREAD

**Issue by janemba** [pop-os/system76-driver#231]
Hello,

I noticed that `system76-driver` use  `system76-adjust-tdp`. But that file is nowhere to be found. Where can I get it ?

**Comment by janemba** [comment]
any update ?

**Comment by jackpot51** [comment]
The source is here: https://github.com/pop-os/system76-driver/blob/7472a0bc81dd3db3a1f89c66678e86f200a8d8af/system76driver/actions.py#L1100

**Comment by janemba** [comment]
Thanks
