### ISSUE TITLE
oryp3-ess headphone jack does not work in Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by ahoneybun** [pop-os/system76-driver#33]
If this is a bug, please use the template below. If this is a question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**

```
 * Distribution - (run ```cat /etc/os-release```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```

**Issue/Bug Description**

The headphone jack is not outputting audio out. 

**Steps to reproduce (if you know)**

1. Load Ubuntu 18.04 with system76 driver
2. Plug in headphones to the first port 
3. Test audio

**Expected behavior**

Audio would come though the headphone jack

**Other Notes**

**Comment by jackpot51** [comment]
Thanks. @djordan2 will be looking into this
