### ISSUE TITLE
HiDPI Daemon Doesn't Respect Custom Resolution Settings

### ISSUE THREAD

**Issue by jlacroix82** [pop-os/system76-driver#8]
**Reporter info**

```
 * Distribution - Ubuntu 17.10 64-bit with S76 driver repo/package installed
 * Related Application and/or Package Version: system76-driver 17.10.11
```

**Issue/Bug Description**
The HiDPI daemon prevents GNOME's multi-monitor configuration from working properly. Normally, when you re-attach a display to your laptop, GNOME will set the previous resolution and layout that you selected for that monitor the last time it was connected. With the HiDPI daemon, the 1600x900 resolution is always applied to the laptop screen (despite manually selecting a different resolution) and the monitor layout that was selected manually is also overridden. This means that every time I go to my desk and plug in an external display, I have to spend time manually applying my custom resolution settings. Before the HiDPI daemon, GNOME would re-apply the previous settings.

**Steps to reproduce (if you know)**
1.) Set custom resolution for your laptop display with NO external display attached (I use 1080p with 100% scaling)
2.) Plug in an external display, keep the laptop open (I used HDMI)
3.) Notice that the resolution of the laptop display will change, even though you manually selected a specific resolution for it
4.) In the GNOME settings utility, customize the external screen resolution (change which side of the laptop screen its on, its resolution, etc)
5.) Disconnect the display
6.) Notice that the laptop display resolution will change again
7.) Notice the custom resolution/layout you chose for the display in step #4 is not reapplied here, you have to do this again

**Expected behavior**
By default, GNOME remembers the previously selected resolution, and reapplies it. If you connect an external display, GNOME remembers the resolution and layout you set for it, and re-applies that as well. The HiDPI daemon basically circumvents GNOME's default behavior, and puts the burden on the user to readjust the display settings every time there is a change.

**Comment by djordan2** [comment]
Fixed in 17.10.23
